#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]
book_list:
    path: /book
    controller: App\Controller\BookController::books
    methods: [GET]


