#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]
book_list:
    path: /book
    controller: App\Controller\LibraryController::books
    methods: [GET]
book_listone:
    path: /book/{id}
    controller: App\Controller\LibraryController::booksOne
    methods: [GET]
controllers:
    resource: ../src/Controller
    type: annotation





