#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]

health_check1:
    path: /che
    controller: App\Controller\HealthCheckController::index1
    methods: [GET]

