#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]

health_check1:
    path: /che
    controller: App\Controller\HealthCheckController::index1
    methods: [GET]
health_check2:
    path: /con
    controller: App\Controller\HealthCheckController::index2
    methods: [GET]

health_check3:
    path: /MiIndice
    controller: App\Controller\ConferenceController::index

