#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]
controler_serv_status:
    path: servstatus
    controller: App\Controller\ConferenceServController::statuscserv
    methods: [GET]
controler_serv:
    path: main
    controller: App\Controller\ConferenceServController::dashBoard
    methods: [GET]




