#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]

list_book:
    path: books
    controller: App\Controller\ConferenceServController::listBook
    methods: [GET]



